project:
  type: website
  output-dir: docs

website:
  title: "Michael Saikali, PhD"
  navbar:
    left:
     - href: index.qmd
       text: Home
     # - href: learn_to_code.qmd
     #   text: Learn to code
     # - href: pksimulator.qmd
     #   text: Pharmacokinetics
     - href: MetaboMiNR.qmd
       text: MetaboMiNR
     - publications.qmd

format:
  html:
    theme: sandstone
    toc: false